/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.Set;

import static hashtable.HashTable.RepeatedWord;

public class App {
    public static void main(String[] args) {

        HashTable ht = new HashTable(1024);
        ht.set("Hashirama", "1st Hokage");
        ht.set("Tobirama", "2nd Hokage");
        ht.set("Hiruzen", "3rd Hokage");
        ht.set("Minato", "4th Hokage");
        ht.set("Tsunade", "5th Hokage");
        ht.set("Kakashi", "6th Hokage");
        ht.set("Naruto", "7th Hokage");

        System.out.println( "Has Hiruzen ... " + ht.has("Hiruzen") );
        System.out.println( "Get Naruto " + ht.get("Naruto") );
        System.out.println( "Get Hiruzen " + ht.get("Hiruzen") );
        System.out.println( "Has Danzo ... " + ht.has("Danzo") );

        //repeatedword
        String test = "The current Hokage is Naruto, the 7th Hokage.";
        Set<String> repeated = RepeatedWord(test);
        System.out.println("input : " + test);
        System.out.println("output : " + repeated);
    }
}
